name = "digitalverse"
compatibility_date = "2026-01-01"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "digitalverse"
database_id = "78a42d35-75ab-4d97-b81f-4f4e91ea79ab"
